version: '3.1'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: europe-docker.pkg.dev/personagenerator-379008/personagenerator/personegenerator:${TAG}
    command: gunicorn --bind 0.0.0.0:8080 app:app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - ~/.aws:/root/.aws
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - APP_USER=${APP_USER}
      - APP_PASSWORD=${APP_PASSWORD}
      - MONGO_URL=${MONGO_URL}

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: tasks
    healthcheck:
        test: mongosh mongo:27017/test --eval 'db.runCommand("ping").ok'
        timeout: 5s
        retries: 10
        start_period: 10s
