# Use root/example as user/password credentials
version: '3.1'

services:
  # proxy:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #       - ./nginx/static:/usr/share/nginx/html/static
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ~/.aws:/root/.aws
    environment:
      # For CI to pass
      OPENAI_API_KEY: ${OPENAI_API_KEY}

