version: '3.1'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    command: python app.py
    depends_on:
      mongo:
        condition: service_healthy
    image: personagetnerator
    ports:
      - 5000:5000
    volumes:
      - ~/.aws:/root/.aws
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - APP_USER=${APP_USER}
      - APP_PASSWORD=${APP_PASSWORD}
      - MONGO_URL=${MONGO_URL}

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      # MONGO_INITDB_DATABASE: tasks
    healthcheck:
        test: mongosh mongo:27017/test --eval 'db.runCommand("ping").ok'
        timeout: 5s
        retries: 10
        start_period: 10s

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
  