name: CI

on:
  push:
    branches: [ "main", "devops", "feature/*" ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
      id: git_clone

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      id: aws_configure
      with:
        role-to-assume: arn:aws:iam::405854541726:role/github-actions-role
        role-session-name: samplerolesession
        aws-region: us-east-2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install dependencies for testing
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Unit Test With pytest
      id: unit_test
      run: | 
        # Creating images directory in order for the test to pass
        pytest test_unit_test

    - name: Build Docker Compose
      id: Build
      run: |
        docker build -t persona:test
        docker compose up -d

    - name: E2E test
      id: E2E
      run: |
        pytest test_e2e
    

    - name: Slack Notification
      uses: act10ns/slack@v2.0.0
      # send message even if the ci fails
      if: always()
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}


  





