name: CI

on:
  push:
    branches: ["devops"]

jobs:
  versionCalc:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
      id: git_clone

    - name: Bump version and push tag
      id: tag
      # Will be changed to master soon
      # if: ${{ github.ref == 'refs/heads/main' }}
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 0.0.0
        DEFAULT_BRANCH: devops

    - name: access_output
      run: |
        echo {{ steps.tag.outputs.new_version }}      
